//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package mobi.tongari.mokutan;

import android.content.Context;
import android.content.SharedPreferences;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class SharedPrefs_
    extends SharedPreferencesHelper
{


    public SharedPrefs_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_SharedPrefs"), 0));
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public SharedPrefs_.SharedPrefsEditor_ edit() {
        return new SharedPrefs_.SharedPrefsEditor_(getSharedPreferences());
    }

    public StringPrefField userName() {
        return stringField("userName", "");
    }

    public final static class SharedPrefsEditor_
        extends EditorHelper<SharedPrefs_.SharedPrefsEditor_>
    {


        SharedPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<SharedPrefs_.SharedPrefsEditor_> userName() {
            return stringField("userName");
        }

    }

}
